// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/mujak27/gamen/src/core/internal/api/dto"
	"github.com/mujak27/gamen/src/core/internal/interfaces/services"
	"github.com/mujak27/gamen/src/core/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCatalogueService creates a new instance of MockCatalogueService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCatalogueService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCatalogueService {
	mock := &MockCatalogueService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCatalogueService is an autogenerated mock type for the CatalogueService type
type MockCatalogueService struct {
	mock.Mock
}

type MockCatalogueService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCatalogueService) EXPECT() *MockCatalogueService_Expecter {
	return &MockCatalogueService_Expecter{mock: &_m.Mock}
}

// GetPluginFunctionById provides a mock function for the type MockCatalogueService
func (_mock *MockCatalogueService) GetPluginFunctionById(id uuid.UUID) (interfaces.PluginService, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetPluginFunctionById")
	}

	var r0 interfaces.PluginService
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (interfaces.PluginService, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) interfaces.PluginService); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.PluginService)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogueService_GetPluginFunctionById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPluginFunctionById'
type MockCatalogueService_GetPluginFunctionById_Call struct {
	*mock.Call
}

// GetPluginFunctionById is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockCatalogueService_Expecter) GetPluginFunctionById(id interface{}) *MockCatalogueService_GetPluginFunctionById_Call {
	return &MockCatalogueService_GetPluginFunctionById_Call{Call: _e.mock.On("GetPluginFunctionById", id)}
}

func (_c *MockCatalogueService_GetPluginFunctionById_Call) Run(run func(id uuid.UUID)) *MockCatalogueService_GetPluginFunctionById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCatalogueService_GetPluginFunctionById_Call) Return(pluginService interfaces.PluginService, err error) *MockCatalogueService_GetPluginFunctionById_Call {
	_c.Call.Return(pluginService, err)
	return _c
}

func (_c *MockCatalogueService_GetPluginFunctionById_Call) RunAndReturn(run func(id uuid.UUID) (interfaces.PluginService, error)) *MockCatalogueService_GetPluginFunctionById_Call {
	_c.Call.Return(run)
	return _c
}

// GetPluginModelById provides a mock function for the type MockCatalogueService
func (_mock *MockCatalogueService) GetPluginModelById(id uuid.UUID) (models.Plugin, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetPluginModelById")
	}

	var r0 models.Plugin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (models.Plugin, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) models.Plugin); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(models.Plugin)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogueService_GetPluginModelById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPluginModelById'
type MockCatalogueService_GetPluginModelById_Call struct {
	*mock.Call
}

// GetPluginModelById is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockCatalogueService_Expecter) GetPluginModelById(id interface{}) *MockCatalogueService_GetPluginModelById_Call {
	return &MockCatalogueService_GetPluginModelById_Call{Call: _e.mock.On("GetPluginModelById", id)}
}

func (_c *MockCatalogueService_GetPluginModelById_Call) Run(run func(id uuid.UUID)) *MockCatalogueService_GetPluginModelById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCatalogueService_GetPluginModelById_Call) Return(plugin models.Plugin, err error) *MockCatalogueService_GetPluginModelById_Call {
	_c.Call.Return(plugin, err)
	return _c
}

func (_c *MockCatalogueService_GetPluginModelById_Call) RunAndReturn(run func(id uuid.UUID) (models.Plugin, error)) *MockCatalogueService_GetPluginModelById_Call {
	_c.Call.Return(run)
	return _c
}

// ListPluginKeys provides a mock function for the type MockCatalogueService
func (_mock *MockCatalogueService) ListPluginKeys() ([]uuid.UUID, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListPluginKeys")
	}

	var r0 []uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]uuid.UUID, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []uuid.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogueService_ListPluginKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPluginKeys'
type MockCatalogueService_ListPluginKeys_Call struct {
	*mock.Call
}

// ListPluginKeys is a helper method to define mock.On call
func (_e *MockCatalogueService_Expecter) ListPluginKeys() *MockCatalogueService_ListPluginKeys_Call {
	return &MockCatalogueService_ListPluginKeys_Call{Call: _e.mock.On("ListPluginKeys")}
}

func (_c *MockCatalogueService_ListPluginKeys_Call) Run(run func()) *MockCatalogueService_ListPluginKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCatalogueService_ListPluginKeys_Call) Return(uUIDs []uuid.UUID, err error) *MockCatalogueService_ListPluginKeys_Call {
	_c.Call.Return(uUIDs, err)
	return _c
}

func (_c *MockCatalogueService_ListPluginKeys_Call) RunAndReturn(run func() ([]uuid.UUID, error)) *MockCatalogueService_ListPluginKeys_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIConfigurationService creates a new instance of MockIConfigurationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIConfigurationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIConfigurationService {
	mock := &MockIConfigurationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIConfigurationService is an autogenerated mock type for the IConfigurationService type
type MockIConfigurationService struct {
	mock.Mock
}

type MockIConfigurationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIConfigurationService) EXPECT() *MockIConfigurationService_Expecter {
	return &MockIConfigurationService_Expecter{mock: &_m.Mock}
}

// CreateConfiguration provides a mock function for the type MockIConfigurationService
func (_mock *MockIConfigurationService) CreateConfiguration(ctx context.Context, payload dto.ConfigurationCreatePayload) (models.Configuration, error) {
	ret := _mock.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for CreateConfiguration")
	}

	var r0 models.Configuration
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ConfigurationCreatePayload) (models.Configuration, error)); ok {
		return returnFunc(ctx, payload)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ConfigurationCreatePayload) models.Configuration); ok {
		r0 = returnFunc(ctx, payload)
	} else {
		r0 = ret.Get(0).(models.Configuration)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.ConfigurationCreatePayload) error); ok {
		r1 = returnFunc(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIConfigurationService_CreateConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateConfiguration'
type MockIConfigurationService_CreateConfiguration_Call struct {
	*mock.Call
}

// CreateConfiguration is a helper method to define mock.On call
//   - ctx context.Context
//   - payload dto.ConfigurationCreatePayload
func (_e *MockIConfigurationService_Expecter) CreateConfiguration(ctx interface{}, payload interface{}) *MockIConfigurationService_CreateConfiguration_Call {
	return &MockIConfigurationService_CreateConfiguration_Call{Call: _e.mock.On("CreateConfiguration", ctx, payload)}
}

func (_c *MockIConfigurationService_CreateConfiguration_Call) Run(run func(ctx context.Context, payload dto.ConfigurationCreatePayload)) *MockIConfigurationService_CreateConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.ConfigurationCreatePayload
		if args[1] != nil {
			arg1 = args[1].(dto.ConfigurationCreatePayload)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIConfigurationService_CreateConfiguration_Call) Return(configuration models.Configuration, err error) *MockIConfigurationService_CreateConfiguration_Call {
	_c.Call.Return(configuration, err)
	return _c
}

func (_c *MockIConfigurationService_CreateConfiguration_Call) RunAndReturn(run func(ctx context.Context, payload dto.ConfigurationCreatePayload) (models.Configuration, error)) *MockIConfigurationService_CreateConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteConfiguration provides a mock function for the type MockIConfigurationService
func (_mock *MockIConfigurationService) DeleteConfiguration(ctx context.Context, payload dto.ConfigurationDeletePayload) error {
	ret := _mock.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConfiguration")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ConfigurationDeletePayload) error); ok {
		r0 = returnFunc(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIConfigurationService_DeleteConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteConfiguration'
type MockIConfigurationService_DeleteConfiguration_Call struct {
	*mock.Call
}

// DeleteConfiguration is a helper method to define mock.On call
//   - ctx context.Context
//   - payload dto.ConfigurationDeletePayload
func (_e *MockIConfigurationService_Expecter) DeleteConfiguration(ctx interface{}, payload interface{}) *MockIConfigurationService_DeleteConfiguration_Call {
	return &MockIConfigurationService_DeleteConfiguration_Call{Call: _e.mock.On("DeleteConfiguration", ctx, payload)}
}

func (_c *MockIConfigurationService_DeleteConfiguration_Call) Run(run func(ctx context.Context, payload dto.ConfigurationDeletePayload)) *MockIConfigurationService_DeleteConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.ConfigurationDeletePayload
		if args[1] != nil {
			arg1 = args[1].(dto.ConfigurationDeletePayload)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIConfigurationService_DeleteConfiguration_Call) Return(err error) *MockIConfigurationService_DeleteConfiguration_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIConfigurationService_DeleteConfiguration_Call) RunAndReturn(run func(ctx context.Context, payload dto.ConfigurationDeletePayload) error) *MockIConfigurationService_DeleteConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfigurationById provides a mock function for the type MockIConfigurationService
func (_mock *MockIConfigurationService) GetConfigurationById(ctx context.Context, payload dto.ConfigurationGetPayload) (models.Configuration, error) {
	ret := _mock.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for GetConfigurationById")
	}

	var r0 models.Configuration
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ConfigurationGetPayload) (models.Configuration, error)); ok {
		return returnFunc(ctx, payload)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ConfigurationGetPayload) models.Configuration); ok {
		r0 = returnFunc(ctx, payload)
	} else {
		r0 = ret.Get(0).(models.Configuration)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.ConfigurationGetPayload) error); ok {
		r1 = returnFunc(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIConfigurationService_GetConfigurationById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfigurationById'
type MockIConfigurationService_GetConfigurationById_Call struct {
	*mock.Call
}

// GetConfigurationById is a helper method to define mock.On call
//   - ctx context.Context
//   - payload dto.ConfigurationGetPayload
func (_e *MockIConfigurationService_Expecter) GetConfigurationById(ctx interface{}, payload interface{}) *MockIConfigurationService_GetConfigurationById_Call {
	return &MockIConfigurationService_GetConfigurationById_Call{Call: _e.mock.On("GetConfigurationById", ctx, payload)}
}

func (_c *MockIConfigurationService_GetConfigurationById_Call) Run(run func(ctx context.Context, payload dto.ConfigurationGetPayload)) *MockIConfigurationService_GetConfigurationById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.ConfigurationGetPayload
		if args[1] != nil {
			arg1 = args[1].(dto.ConfigurationGetPayload)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIConfigurationService_GetConfigurationById_Call) Return(configuration models.Configuration, err error) *MockIConfigurationService_GetConfigurationById_Call {
	_c.Call.Return(configuration, err)
	return _c
}

func (_c *MockIConfigurationService_GetConfigurationById_Call) RunAndReturn(run func(ctx context.Context, payload dto.ConfigurationGetPayload) (models.Configuration, error)) *MockIConfigurationService_GetConfigurationById_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfigurationTypeById provides a mock function for the type MockIConfigurationService
func (_mock *MockIConfigurationService) GetConfigurationTypeById(id uuid.UUID) (models.ConfigurationType, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetConfigurationTypeById")
	}

	var r0 models.ConfigurationType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (models.ConfigurationType, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) models.ConfigurationType); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(models.ConfigurationType)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIConfigurationService_GetConfigurationTypeById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfigurationTypeById'
type MockIConfigurationService_GetConfigurationTypeById_Call struct {
	*mock.Call
}

// GetConfigurationTypeById is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockIConfigurationService_Expecter) GetConfigurationTypeById(id interface{}) *MockIConfigurationService_GetConfigurationTypeById_Call {
	return &MockIConfigurationService_GetConfigurationTypeById_Call{Call: _e.mock.On("GetConfigurationTypeById", id)}
}

func (_c *MockIConfigurationService_GetConfigurationTypeById_Call) Run(run func(id uuid.UUID)) *MockIConfigurationService_GetConfigurationTypeById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIConfigurationService_GetConfigurationTypeById_Call) Return(configurationType models.ConfigurationType, err error) *MockIConfigurationService_GetConfigurationTypeById_Call {
	_c.Call.Return(configurationType, err)
	return _c
}

func (_c *MockIConfigurationService_GetConfigurationTypeById_Call) RunAndReturn(run func(id uuid.UUID) (models.ConfigurationType, error)) *MockIConfigurationService_GetConfigurationTypeById_Call {
	_c.Call.Return(run)
	return _c
}

// ListConfigurationTypes provides a mock function for the type MockIConfigurationService
func (_mock *MockIConfigurationService) ListConfigurationTypes() ([]models.ConfigurationType, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListConfigurationTypes")
	}

	var r0 []models.ConfigurationType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.ConfigurationType, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.ConfigurationType); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ConfigurationType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIConfigurationService_ListConfigurationTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListConfigurationTypes'
type MockIConfigurationService_ListConfigurationTypes_Call struct {
	*mock.Call
}

// ListConfigurationTypes is a helper method to define mock.On call
func (_e *MockIConfigurationService_Expecter) ListConfigurationTypes() *MockIConfigurationService_ListConfigurationTypes_Call {
	return &MockIConfigurationService_ListConfigurationTypes_Call{Call: _e.mock.On("ListConfigurationTypes")}
}

func (_c *MockIConfigurationService_ListConfigurationTypes_Call) Run(run func()) *MockIConfigurationService_ListConfigurationTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIConfigurationService_ListConfigurationTypes_Call) Return(configurationTypes []models.ConfigurationType, err error) *MockIConfigurationService_ListConfigurationTypes_Call {
	_c.Call.Return(configurationTypes, err)
	return _c
}

func (_c *MockIConfigurationService_ListConfigurationTypes_Call) RunAndReturn(run func() ([]models.ConfigurationType, error)) *MockIConfigurationService_ListConfigurationTypes_Call {
	_c.Call.Return(run)
	return _c
}

// ListConfigurations provides a mock function for the type MockIConfigurationService
func (_mock *MockIConfigurationService) ListConfigurations(ctx context.Context, payload dto.ConfigurationListPayload) ([]models.Configuration, error) {
	ret := _mock.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for ListConfigurations")
	}

	var r0 []models.Configuration
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ConfigurationListPayload) ([]models.Configuration, error)); ok {
		return returnFunc(ctx, payload)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ConfigurationListPayload) []models.Configuration); ok {
		r0 = returnFunc(ctx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Configuration)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.ConfigurationListPayload) error); ok {
		r1 = returnFunc(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIConfigurationService_ListConfigurations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListConfigurations'
type MockIConfigurationService_ListConfigurations_Call struct {
	*mock.Call
}

// ListConfigurations is a helper method to define mock.On call
//   - ctx context.Context
//   - payload dto.ConfigurationListPayload
func (_e *MockIConfigurationService_Expecter) ListConfigurations(ctx interface{}, payload interface{}) *MockIConfigurationService_ListConfigurations_Call {
	return &MockIConfigurationService_ListConfigurations_Call{Call: _e.mock.On("ListConfigurations", ctx, payload)}
}

func (_c *MockIConfigurationService_ListConfigurations_Call) Run(run func(ctx context.Context, payload dto.ConfigurationListPayload)) *MockIConfigurationService_ListConfigurations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.ConfigurationListPayload
		if args[1] != nil {
			arg1 = args[1].(dto.ConfigurationListPayload)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIConfigurationService_ListConfigurations_Call) Return(configurations []models.Configuration, err error) *MockIConfigurationService_ListConfigurations_Call {
	_c.Call.Return(configurations, err)
	return _c
}

func (_c *MockIConfigurationService_ListConfigurations_Call) RunAndReturn(run func(ctx context.Context, payload dto.ConfigurationListPayload) ([]models.Configuration, error)) *MockIConfigurationService_ListConfigurations_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateConfiguration provides a mock function for the type MockIConfigurationService
func (_mock *MockIConfigurationService) UpdateConfiguration(ctx context.Context, payload dto.ConfigurationUpdatePayload) (models.Configuration, error) {
	ret := _mock.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConfiguration")
	}

	var r0 models.Configuration
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ConfigurationUpdatePayload) (models.Configuration, error)); ok {
		return returnFunc(ctx, payload)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ConfigurationUpdatePayload) models.Configuration); ok {
		r0 = returnFunc(ctx, payload)
	} else {
		r0 = ret.Get(0).(models.Configuration)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.ConfigurationUpdatePayload) error); ok {
		r1 = returnFunc(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIConfigurationService_UpdateConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateConfiguration'
type MockIConfigurationService_UpdateConfiguration_Call struct {
	*mock.Call
}

// UpdateConfiguration is a helper method to define mock.On call
//   - ctx context.Context
//   - payload dto.ConfigurationUpdatePayload
func (_e *MockIConfigurationService_Expecter) UpdateConfiguration(ctx interface{}, payload interface{}) *MockIConfigurationService_UpdateConfiguration_Call {
	return &MockIConfigurationService_UpdateConfiguration_Call{Call: _e.mock.On("UpdateConfiguration", ctx, payload)}
}

func (_c *MockIConfigurationService_UpdateConfiguration_Call) Run(run func(ctx context.Context, payload dto.ConfigurationUpdatePayload)) *MockIConfigurationService_UpdateConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.ConfigurationUpdatePayload
		if args[1] != nil {
			arg1 = args[1].(dto.ConfigurationUpdatePayload)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIConfigurationService_UpdateConfiguration_Call) Return(configuration models.Configuration, err error) *MockIConfigurationService_UpdateConfiguration_Call {
	_c.Call.Return(configuration, err)
	return _c
}

func (_c *MockIConfigurationService_UpdateConfiguration_Call) RunAndReturn(run func(ctx context.Context, payload dto.ConfigurationUpdatePayload) (models.Configuration, error)) *MockIConfigurationService_UpdateConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIConfigurationTypeService creates a new instance of MockIConfigurationTypeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIConfigurationTypeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIConfigurationTypeService {
	mock := &MockIConfigurationTypeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIConfigurationTypeService is an autogenerated mock type for the IConfigurationTypeService type
type MockIConfigurationTypeService struct {
	mock.Mock
}

type MockIConfigurationTypeService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIConfigurationTypeService) EXPECT() *MockIConfigurationTypeService_Expecter {
	return &MockIConfigurationTypeService_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockIConfigurationTypeService
func (_mock *MockIConfigurationTypeService) Get() models.ConfigurationType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 models.ConfigurationType
	if returnFunc, ok := ret.Get(0).(func() models.ConfigurationType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(models.ConfigurationType)
	}
	return r0
}

// MockIConfigurationTypeService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIConfigurationTypeService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockIConfigurationTypeService_Expecter) Get() *MockIConfigurationTypeService_Get_Call {
	return &MockIConfigurationTypeService_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *MockIConfigurationTypeService_Get_Call) Run(run func()) *MockIConfigurationTypeService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIConfigurationTypeService_Get_Call) Return(configurationType models.ConfigurationType) *MockIConfigurationTypeService_Get_Call {
	_c.Call.Return(configurationType)
	return _c
}

func (_c *MockIConfigurationTypeService_Get_Call) RunAndReturn(run func() models.ConfigurationType) *MockIConfigurationTypeService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetId provides a mock function for the type MockIConfigurationTypeService
func (_mock *MockIConfigurationTypeService) GetId() uuid.UUID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetId")
	}

	var r0 uuid.UUID
	if returnFunc, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	return r0
}

// MockIConfigurationTypeService_GetId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetId'
type MockIConfigurationTypeService_GetId_Call struct {
	*mock.Call
}

// GetId is a helper method to define mock.On call
func (_e *MockIConfigurationTypeService_Expecter) GetId() *MockIConfigurationTypeService_GetId_Call {
	return &MockIConfigurationTypeService_GetId_Call{Call: _e.mock.On("GetId")}
}

func (_c *MockIConfigurationTypeService_GetId_Call) Run(run func()) *MockIConfigurationTypeService_GetId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIConfigurationTypeService_GetId_Call) Return(uUID uuid.UUID) *MockIConfigurationTypeService_GetId_Call {
	_c.Call.Return(uUID)
	return _c
}

func (_c *MockIConfigurationTypeService_GetId_Call) RunAndReturn(run func() uuid.UUID) *MockIConfigurationTypeService_GetId_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateConfiguration provides a mock function for the type MockIConfigurationTypeService
func (_mock *MockIConfigurationTypeService) ValidateConfiguration(configuration models.Configuration) error {
	ret := _mock.Called(configuration)

	if len(ret) == 0 {
		panic("no return value specified for ValidateConfiguration")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(models.Configuration) error); ok {
		r0 = returnFunc(configuration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIConfigurationTypeService_ValidateConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateConfiguration'
type MockIConfigurationTypeService_ValidateConfiguration_Call struct {
	*mock.Call
}

// ValidateConfiguration is a helper method to define mock.On call
//   - configuration models.Configuration
func (_e *MockIConfigurationTypeService_Expecter) ValidateConfiguration(configuration interface{}) *MockIConfigurationTypeService_ValidateConfiguration_Call {
	return &MockIConfigurationTypeService_ValidateConfiguration_Call{Call: _e.mock.On("ValidateConfiguration", configuration)}
}

func (_c *MockIConfigurationTypeService_ValidateConfiguration_Call) Run(run func(configuration models.Configuration)) *MockIConfigurationTypeService_ValidateConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.Configuration
		if args[0] != nil {
			arg0 = args[0].(models.Configuration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIConfigurationTypeService_ValidateConfiguration_Call) Return(err error) *MockIConfigurationTypeService_ValidateConfiguration_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIConfigurationTypeService_ValidateConfiguration_Call) RunAndReturn(run func(configuration models.Configuration) error) *MockIConfigurationTypeService_ValidateConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPluginService creates a new instance of MockPluginService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPluginService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPluginService {
	mock := &MockPluginService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPluginService is an autogenerated mock type for the PluginService type
type MockPluginService struct {
	mock.Mock
}

type MockPluginService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPluginService) EXPECT() *MockPluginService_Expecter {
	return &MockPluginService_Expecter{mock: &_m.Mock}
}

// Action provides a mock function for the type MockPluginService
func (_mock *MockPluginService) Action(pluginActionSchema dto.PluginActionSchema) error {
	ret := _mock.Called(pluginActionSchema)

	if len(ret) == 0 {
		panic("no return value specified for Action")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(dto.PluginActionSchema) error); ok {
		r0 = returnFunc(pluginActionSchema)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPluginService_Action_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Action'
type MockPluginService_Action_Call struct {
	*mock.Call
}

// Action is a helper method to define mock.On call
//   - pluginActionSchema dto.PluginActionSchema
func (_e *MockPluginService_Expecter) Action(pluginActionSchema interface{}) *MockPluginService_Action_Call {
	return &MockPluginService_Action_Call{Call: _e.mock.On("Action", pluginActionSchema)}
}

func (_c *MockPluginService_Action_Call) Run(run func(pluginActionSchema dto.PluginActionSchema)) *MockPluginService_Action_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dto.PluginActionSchema
		if args[0] != nil {
			arg0 = args[0].(dto.PluginActionSchema)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPluginService_Action_Call) Return(err error) *MockPluginService_Action_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPluginService_Action_Call) RunAndReturn(run func(pluginActionSchema dto.PluginActionSchema) error) *MockPluginService_Action_Call {
	_c.Call.Return(run)
	return _c
}

// ActionValidatePayload provides a mock function for the type MockPluginService
func (_mock *MockPluginService) ActionValidatePayload(pluginActionSchema dto.PluginActionSchema) error {
	ret := _mock.Called(pluginActionSchema)

	if len(ret) == 0 {
		panic("no return value specified for ActionValidatePayload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(dto.PluginActionSchema) error); ok {
		r0 = returnFunc(pluginActionSchema)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPluginService_ActionValidatePayload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActionValidatePayload'
type MockPluginService_ActionValidatePayload_Call struct {
	*mock.Call
}

// ActionValidatePayload is a helper method to define mock.On call
//   - pluginActionSchema dto.PluginActionSchema
func (_e *MockPluginService_Expecter) ActionValidatePayload(pluginActionSchema interface{}) *MockPluginService_ActionValidatePayload_Call {
	return &MockPluginService_ActionValidatePayload_Call{Call: _e.mock.On("ActionValidatePayload", pluginActionSchema)}
}

func (_c *MockPluginService_ActionValidatePayload_Call) Run(run func(pluginActionSchema dto.PluginActionSchema)) *MockPluginService_ActionValidatePayload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dto.PluginActionSchema
		if args[0] != nil {
			arg0 = args[0].(dto.PluginActionSchema)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPluginService_ActionValidatePayload_Call) Return(err error) *MockPluginService_ActionValidatePayload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPluginService_ActionValidatePayload_Call) RunAndReturn(run func(pluginActionSchema dto.PluginActionSchema) error) *MockPluginService_ActionValidatePayload_Call {
	_c.Call.Return(run)
	return _c
}

// Fetch provides a mock function for the type MockPluginService
func (_mock *MockPluginService) Fetch(s string) (dto.PluginFetchSchema, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 dto.PluginFetchSchema
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (dto.PluginFetchSchema, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) dto.PluginFetchSchema); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(dto.PluginFetchSchema)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPluginService_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockPluginService_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - s string
func (_e *MockPluginService_Expecter) Fetch(s interface{}) *MockPluginService_Fetch_Call {
	return &MockPluginService_Fetch_Call{Call: _e.mock.On("Fetch", s)}
}

func (_c *MockPluginService_Fetch_Call) Run(run func(s string)) *MockPluginService_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPluginService_Fetch_Call) Return(pluginFetchSchema dto.PluginFetchSchema, err error) *MockPluginService_Fetch_Call {
	_c.Call.Return(pluginFetchSchema, err)
	return _c
}

func (_c *MockPluginService_Fetch_Call) RunAndReturn(run func(s string) (dto.PluginFetchSchema, error)) *MockPluginService_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockPluginService
func (_mock *MockPluginService) Get() (models.Plugin, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 models.Plugin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (models.Plugin, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() models.Plugin); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(models.Plugin)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPluginService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPluginService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockPluginService_Expecter) Get() *MockPluginService_Get_Call {
	return &MockPluginService_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *MockPluginService_Get_Call) Run(run func()) *MockPluginService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPluginService_Get_Call) Return(plugin models.Plugin, err error) *MockPluginService_Get_Call {
	_c.Call.Return(plugin, err)
	return _c
}

func (_c *MockPluginService_Get_Call) RunAndReturn(run func() (models.Plugin, error)) *MockPluginService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetId provides a mock function for the type MockPluginService
func (_mock *MockPluginService) GetId() uuid.UUID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetId")
	}

	var r0 uuid.UUID
	if returnFunc, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	return r0
}

// MockPluginService_GetId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetId'
type MockPluginService_GetId_Call struct {
	*mock.Call
}

// GetId is a helper method to define mock.On call
func (_e *MockPluginService_Expecter) GetId() *MockPluginService_GetId_Call {
	return &MockPluginService_GetId_Call{Call: _e.mock.On("GetId")}
}

func (_c *MockPluginService_GetId_Call) Run(run func()) *MockPluginService_GetId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPluginService_GetId_Call) Return(uUID uuid.UUID) *MockPluginService_GetId_Call {
	_c.Call.Return(uUID)
	return _c
}

func (_c *MockPluginService_GetId_Call) RunAndReturn(run func() uuid.UUID) *MockPluginService_GetId_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIUserService creates a new instance of MockIUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUserService {
	mock := &MockIUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIUserService is an autogenerated mock type for the IUserService type
type MockIUserService struct {
	mock.Mock
}

type MockIUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUserService) EXPECT() *MockIUserService_Expecter {
	return &MockIUserService_Expecter{mock: &_m.Mock}
}

// IsTeamMember provides a mock function for the type MockIUserService
func (_mock *MockIUserService) IsTeamMember(userId uuid.UUID, teamId uuid.UUID) (bool, error) {
	ret := _mock.Called(userId, teamId)

	if len(ret) == 0 {
		panic("no return value specified for IsTeamMember")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) (bool, error)); ok {
		return returnFunc(userId, teamId)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) bool); ok {
		r0 = returnFunc(userId, teamId)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(userId, teamId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserService_IsTeamMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTeamMember'
type MockIUserService_IsTeamMember_Call struct {
	*mock.Call
}

// IsTeamMember is a helper method to define mock.On call
//   - userId uuid.UUID
//   - teamId uuid.UUID
func (_e *MockIUserService_Expecter) IsTeamMember(userId interface{}, teamId interface{}) *MockIUserService_IsTeamMember_Call {
	return &MockIUserService_IsTeamMember_Call{Call: _e.mock.On("IsTeamMember", userId, teamId)}
}

func (_c *MockIUserService_IsTeamMember_Call) Run(run func(userId uuid.UUID, teamId uuid.UUID)) *MockIUserService_IsTeamMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserService_IsTeamMember_Call) Return(b bool, err error) *MockIUserService_IsTeamMember_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIUserService_IsTeamMember_Call) RunAndReturn(run func(userId uuid.UUID, teamId uuid.UUID) (bool, error)) *MockIUserService_IsTeamMember_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockIUserService
func (_mock *MockIUserService) Login(loginRequest dto.LoginRequest) (*dto.LoginResponse, error) {
	ret := _mock.Called(loginRequest)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *dto.LoginResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(dto.LoginRequest) (*dto.LoginResponse, error)); ok {
		return returnFunc(loginRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(dto.LoginRequest) *dto.LoginResponse); ok {
		r0 = returnFunc(loginRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.LoginResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(dto.LoginRequest) error); ok {
		r1 = returnFunc(loginRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockIUserService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - loginRequest dto.LoginRequest
func (_e *MockIUserService_Expecter) Login(loginRequest interface{}) *MockIUserService_Login_Call {
	return &MockIUserService_Login_Call{Call: _e.mock.On("Login", loginRequest)}
}

func (_c *MockIUserService_Login_Call) Run(run func(loginRequest dto.LoginRequest)) *MockIUserService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dto.LoginRequest
		if args[0] != nil {
			arg0 = args[0].(dto.LoginRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUserService_Login_Call) Return(loginResponse *dto.LoginResponse, err error) *MockIUserService_Login_Call {
	_c.Call.Return(loginResponse, err)
	return _c
}

func (_c *MockIUserService_Login_Call) RunAndReturn(run func(loginRequest dto.LoginRequest) (*dto.LoginResponse, error)) *MockIUserService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockIUserService
func (_mock *MockIUserService) Register(registerRequest dto.RegisterRequest) (*models.User, error) {
	ret := _mock.Called(registerRequest)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(dto.RegisterRequest) (*models.User, error)); ok {
		return returnFunc(registerRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(dto.RegisterRequest) *models.User); ok {
		r0 = returnFunc(registerRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(dto.RegisterRequest) error); ok {
		r1 = returnFunc(registerRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockIUserService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - registerRequest dto.RegisterRequest
func (_e *MockIUserService_Expecter) Register(registerRequest interface{}) *MockIUserService_Register_Call {
	return &MockIUserService_Register_Call{Call: _e.mock.On("Register", registerRequest)}
}

func (_c *MockIUserService_Register_Call) Run(run func(registerRequest dto.RegisterRequest)) *MockIUserService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dto.RegisterRequest
		if args[0] != nil {
			arg0 = args[0].(dto.RegisterRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUserService_Register_Call) Return(user *models.User, err error) *MockIUserService_Register_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserService_Register_Call) RunAndReturn(run func(registerRequest dto.RegisterRequest) (*models.User, error)) *MockIUserService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWidgetService creates a new instance of MockWidgetService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWidgetService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWidgetService {
	mock := &MockWidgetService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWidgetService is an autogenerated mock type for the WidgetService type
type MockWidgetService struct {
	mock.Mock
}

type MockWidgetService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWidgetService) EXPECT() *MockWidgetService_Expecter {
	return &MockWidgetService_Expecter{mock: &_m.Mock}
}

// Action provides a mock function for the type MockWidgetService
func (_mock *MockWidgetService) Action(widgetActionPayload dto.WidgetActionPayload) error {
	ret := _mock.Called(widgetActionPayload)

	if len(ret) == 0 {
		panic("no return value specified for Action")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(dto.WidgetActionPayload) error); ok {
		r0 = returnFunc(widgetActionPayload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWidgetService_Action_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Action'
type MockWidgetService_Action_Call struct {
	*mock.Call
}

// Action is a helper method to define mock.On call
//   - widgetActionPayload dto.WidgetActionPayload
func (_e *MockWidgetService_Expecter) Action(widgetActionPayload interface{}) *MockWidgetService_Action_Call {
	return &MockWidgetService_Action_Call{Call: _e.mock.On("Action", widgetActionPayload)}
}

func (_c *MockWidgetService_Action_Call) Run(run func(widgetActionPayload dto.WidgetActionPayload)) *MockWidgetService_Action_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dto.WidgetActionPayload
		if args[0] != nil {
			arg0 = args[0].(dto.WidgetActionPayload)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWidgetService_Action_Call) Return(err error) *MockWidgetService_Action_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWidgetService_Action_Call) RunAndReturn(run func(widgetActionPayload dto.WidgetActionPayload) error) *MockWidgetService_Action_Call {
	_c.Call.Return(run)
	return _c
}
